### ISSUE TITLE
Should we delete merged branches?

### ISSUE THREAD

**Issue by ice1000** [risingwavelabs/rfcs#44]
I have deleted several branches just now manually before I realized it is possible that they're not deleted with intention.

Am I right or wrong?

List of deleted branches (rip):

```
~/git-repos/rfcs/rfcs (tiz/pretty) λ> git fetch --prune --tags --force --progress --all
Fetching origin
From https://github.com/risingwavelabs/rfcs
 - [deleted]         (none)     -> origin/dylan/use_backfill_to_make_mv_on_mv_streaming_again
 - [deleted]         (none)     -> origin/sts/DML
 - [deleted]         (none)     -> origin/sts/fix_file_name
 - [deleted]         (none)     -> origin/xxchan-patch-2
 - ```

**Comment by xxchan** [comment]
![5A099D73-8D51-4EF4-98F9-D9451CCFF48F](https://user-images.githubusercontent.com/37948597/215984525-6930db42-6fe4-4d90-95a8-72d64907f2f1.png)
